### ISSUE TITLE
update when concepticon is >2.3.0

### ISSUE THREAD

**Issue by LinguList** [lexibank/leekoreanic#3]

**Comment by SimonGreenhill** [comment]
Already done: https://github.com/concepticon/concepticon-data/blob/master/concepticondata/conceptlists/Lee-2015-246.tsv but it missed the last release.

**Comment by LinguList** [comment]
I just refined the orthoprofile, but the conceptlist should be updated. @tresoldi, can you look into this?

**Comment by tresoldi** [comment]
I can, but I am missing your branch. Should I wait for you to push it or merge to master?

**Comment by LinguList** [comment]
will push in a second
